/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.67.0
  Forc version: 0.46.1
  Fuel-Core version: 0.20.8
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

interface MyContractAbiInterface extends Interface {
  functions: {
    return_true: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'return_true', values: [BigNumberish]): Uint8Array;

  decodeFunctionData(functionFragment: 'return_true', data: BytesLike): DecodedValue;
}

export class MyContractAbi extends Contract {
  interface: MyContractAbiInterface;
  functions: {
    return_true: InvokeFunction<[val1: BigNumberish], BN>;
  };
}
